### ISSUE TITLE
Wrong onsets and offsets values in continuity_segmentation

### ISSUE THREAD

**Issue by swasun** [timsainb/vocalization-segmentation#5]
Hi,

I am using the function `continuity_segmentation()` to segment vocalizations. I tweaked the parameters in order to obtain what I want to segment, base on the visualization of `plot_labelled_elements()`. Now I am trying to extract the actual sounds, using the positions stored in `onsets` and `offsets` variables. However they seem to not have been updated according to all the parameters of `continuity_segmentation()`. Indeed, they are updated at https://github.com/timsainb/vocalization-segmentation/blob/9e98868234be331b43013ee275d24c2c2bb03fdf/vocalseg/continuity_filtering.py#L92, but not after the `elements` modifications, for example at https://github.com/timsainb/vocalization-segmentation/blob/9e98868234be331b43013ee275d24c2c2bb03fdf/vocalseg/continuity_filtering.py#L157 and https://github.com/timsainb/vocalization-segmentation/blob/9e98868234be331b43013ee275d24c2c2bb03fdf/vocalseg/continuity_filtering.py#L187.

**Comment by timsainb** [comment]
This should be fixed in the new commit https://github.com/timsainb/vocalization-segmentation/pull/6

**Comment by swasun** [comment]
It's working, thanks a lot!
